= OpenNMS Install

This script is a convenient bootstrap script to install OpenNMS on Debian or CentOS systems.
The script executes the steps documented in link:https://docs.opennms.com/horizon/latest/deployment/core/getting-started.html[Installation and Configuration guide].

The script is tested with:

* Ubuntu 22.04.2 (Jammy) 64bit
* Debian 12 (Bookworm) 64bit
* Rocky Linux 9 64bit

== Usage

Download the script to your system.

.Execute on CentOS system
[source, bash]
----
sudo bash bootstrap-yum.sh
----

.Execute on Ubuntu or Debian system
[source, bash]
----
sudo bash bootstrap-debian.sh
----

On Debian it is required to install the `gnupg` package to be able to install the repository key.

== Installing other releases

It is possible to install different releases of OpenNMS.
The script can set a parameter `-r` which overwrites the default release name `stable`.

.Example installing snapshot on Ubuntu
[source, bash]
----
sudo bash bootstrap-debian.sh -r snapshot
----

.Example installing from Business Service Monitor branch
[source, bash]
----
sudo bash bootstrap-debian.sh -r branches/features-bsm
----

== Install from different package mirror

If you want to install from different package mirror, you can overwrite the default `{yum,debian}.mirrors.opennms.org` with your own server.

.Example installing from OpenNMS server in EU
[source, bash]
----
sudo bash bootstrap-debian.sh -m your-server-fqdn
----
